apiVersion: v1
kind: Service
metadata:
  name: mongodb-standalone
  namespace: ibtikarchart
spec:
  selector:
    app: mongodb-standalone
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-standalone
  namespace: ibtikarchart
spec:
  
  selector:
    matchLabels:
      app: mongodb-standalone
  template:
    metadata:
      labels:
        app: mongodb-standalone
    spec:
      containers:
        - name: mongodb
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
