ports:
  web:
    port: 80
  websecure:
    port: 443

additionalArguments:
  - "--entrypoints.websecure.address=:443"

service:
  type: LoadBalancer

providers:
  kubernetesCRD:
    enabled: true
