apiVersion: v2
name: govcom
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: rocketchat
    version: 6.25.2
    repository: "file://charts/rocketchat"
  - name: dashboard
    version: "0.1.0"
    repository: "file://charts/dashboard"
    
