name: Deploy ibtikarchart to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  helm-deploy:
    name: Helm Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_FILE }}" | base64 -d > ~/.kube/config

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.14.0

    - name: Helm dependency update
      run: helm dependency update .

    - name: Helm upgrade
      run: helm upgrade --install ibtikarchart . -n ibtikarchart --create-namespace
