name: Deploy ibtikarchart to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Helm dependency update
      run: helm dependency update ./ibtikarchart

    - name: Deploy with Helm
      run: helm upgrade --install ibtikarchart ./ibtikarchart -n ibtikarchart --create-namespace
