name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > ~/.kube/config

    - name: Deploy with Helm
      run: |
        helm dependency update ibtikarchart .
        helm upgrade --install ibtikarchart ibtikarchart -n ibtikarchart --create-namespace

